export interface PresentationEntry {
  id: number
  text: string
}

export interface InvitedLectureGroups {
  localRegional: PresentationEntry[]
  national: PresentationEntry[]
  international: PresentationEntry[]
  intramural: PresentationEntry[]
}

export const presentationsSource = "CURRICULUM VITAE TJFormat - DThomas_2026-03-03.pdf"

export const invitedLectures: InvitedLectureGroups = {
  localRegional: [
    { id: 1, text: "February 2nd, 2026, \"AI in Action: Practical Applications of Artificial Intelligence in Cancer Research\", Cancer Research Training and Education Coordination (CRTEC) Seminar Series, Sidney Kimmel Comprehensive Cancer Center." },
    { id: 2, text: "September 8th, 2023, \"Computer vision enhanced breast DIBH-RT\", Wings of Hope 11th Annual Evening of Hope, Aurora, CO." },
    { id: 3, text: "December 1st, 2022, \"Hitting a moving target: visualizing and guiding Radiation Therapy\", University of Colorado Boulder, Biomedical Engineering Seminar, Boulder, CO." },
  ],
  national: [
    { id: 1, text: "October 28th, 2025, Foundations of AI for Cancer Training: Building Knowledge, Ensuring Integrity, and Navigating Policy, 21st Annual Cancer Biology Retreat, Cancer Biology Training Consortium" },
    { id: 2, text: "July 2024. \"Analysis of the Accuracy of Computer Vision Assisted Surface-Guided Radiation Therapy\"., 66th American Association of Physicists in Medicine (AAPM) Annual Meeting and Exhibition, SCIENCE COUNCIL SESSION: INNOVATIONS IN MEDICAL PHYSICS. [SENIOR AUTHOR]" },
    { id: 3, text: "July 2023, \"Computer Vision Assisted Alignment for SBRT\", 65th American Association of Physicists in Medicine (AAPM) Annual Meeting and Exhibition - BEST IN PHYSICS SESSION. [SENIOR AUTHOR]." },
    { id: 4, text: "May, 2023, \"Computer Vision assisted Collision Avoidance for Radiation Therapy\", American Radium Society, Lahaina, Hi." },
    { id: 5, text: "May 2020, \"A fast and effective denoising solution using deep learning for real-time X-ray Acoustic Computed Tomography\", American Physical Society, Denver, CO." },
    { id: 6, text: "May 2020, \"Analysis of experimental acoustic waves induced by high-energy pulsed X-ray beams\", American Physical Society, Denver, CO. [SENIOR AUTHOR]." },
    { id: 7, text: "July 2020, \"Effect of X-Ray Irradiation on the Ultrasound Imaging Signal of a Novel Photoacoustic Contrast Agent\". AAPM, American Association of Physicists in Medicine (AAPM) Annual Meeting and Exhibition, Washington DC [SENIOR AUTHOR]" },
    { id: 8, text: "May 1st, 2016, \"MRgRT Adaptive dose prediction\", Norm Baily Research Award Seminar, AAPM Southern California Chapter, San Diego, CA." },
    { id: 9, text: "December 12, 2015 \"5D-CT, clinical implementation of an advanced motion management technique\", Memorial Sloan Kettering Medical Physics Research Seminar, NY." },
    { id: 10, text: "August 1st, 2014, \"A novel 4D CT acquisition and analysis technique\", Joint MGH / Brigham and Women's Hospital Physics Seminar." },
    { id: 11, text: "January 3rd, 2014 \"A novel 4D CT acquisition and analysis technique\", Stanford Medical Physics Resident Seminar (job talk), Stanford, CA." },
    { id: 12, text: "January 5th, 2014, \"Acquisition and analysis of 5DCT\", Medical Physics Resident Seminar (job talk), University of California San Diego, CA." },
    { id: 13, text: "January 15th, 2014 \"A novel 4D CT acquisition and analysis technique\", Medical Physics Resident Application Seminar (job talk), University of California San Francisco, CA." },
    { id: 14, text: "July 15th 2013, \"A Novel 4D CT Acquisition and Analysis Technique to Generate Low Noise Artifact Free Images at User Selected Breathing Phases\". Best in physics Session, 55th Annual Meeting and Exhibition, Indianapolis, IN." },
  ],
  international: [
    { id: 1, text: "February 2023, \"SMPL:RadOnc: application of Max Planck's Skin Mesh model for Radiation Therapy\", Max Plank Exploratory Research Meeting, Perceiving Systems, Max Planck Institute for Intelligent Systems, Stuttgart, Germany." },
    { id: 2, text: "April 2019, \"System Management for Research Ultrasound\", Working Group meeting, Information Engineering Department, Laboratorio Progettazione Sistemi Elettronici, University of Florence, Florence Italy." },
  ],
  intramural: [
    { id: 1, text: "October 18, 2024, \"From Avatars to Digital Twins: Bringing Computer Vision to Patient Alignment\", Division of Medical Physics Retreat, TJUH." },
    { id: 2, text: "October 4th, 2024, \"Computer vision enhanced breast DIBH-RT\", Investigator Initiated Trial Incubator meeting, University of Colorado Anschutz Medical Campus, Aurora, CO." },
    { id: 3, text: "June 5th, 2024, \"Computer vision enhanced breast DIBH-RT\", Radiation Oncology Faculty Meeting Research Presentation, University of Colorado Anschutz Medical Campus, Aurora, CO." },
    { id: 4, text: "September 29, 2023, \"Validation of Computer Vision Assisted Alignment in Radiation Therapy\", Biomechanical Engineering Masters Project Pitch Night, Aurora, CO." },
    { id: 5, text: "December 1st, 2015, \"Advances in 4D-CT: Acquisition, Analysis and Applications\", Radiation Oncology Resident Seminar, University of Colorado Los Angeles, LA, CA." },
  ],
}

export const abstractPresentations: PresentationEntry[] = [
  { id: 1, text: "Atharva Rajesh Peshkar, Danna Gurari, Sarah Milgrom, Willem Schreuder, Moyed Miften, and DH Thomas, 66th American Association of Physicists in Medicine (AAPM) Annual Meeting and Exhibition - SCIENCE COUNCIL SESSION: INNOVATIONS IN MEDICAL PHYSICS - \"Analysis of the Accuracy of Computer Vision Assisted Surface-Guided Radiation Therapy\"." },
  { id: 2, text: "Atharva Peshkar, D Gurari, DH Thomas, 65th American Association of Physicists in Medicine (AAPM) Annual Meeting and Exhibition - BEST IN PHYSICS - \"Computer Vision Assisted Alignment for SBRT\"., 2023 July." },
  { id: 3, text: "DH Thomas, Moyed Miften, Brian Kavanagh, Bernard Trip Jones, American Radium Society, Lahaina, Hi. \"Computer Vision assisted Collision Avoidance for Radiation Therapy\", 2023 May." },
  { id: 4, text: "Will Franz, M Borden, DH Thomas, 65th American Association of Physicists in Medicine (AAPM) Annual Meeting and Exhibition - \"Vaporizable Endoskeletal Droplets for In Vivo Dosimetry.\" Accepted for oral presentation on 7/23/23. Link to conference: https://w4.aapm.org/meetings/2023AM/" },
  { id: 5, text: "Will Franz, DH Thomas, M Borden, 97th ACS Colloid and Surface Science Symposium - \"Vaporizable endoskeletal droplets for contrast enhanced x-ray acoustic imaging.\" Accepted for poster presentation on 4/10/23. Link to conference: https://conferences.coned.ncsu.edu/colloids2023/" },
  { id: 6, text: "Will Franz, DH Thomas, M Borden, Summer Biomechanics, Bioengineering, and Biotransport Conference (SB3C) - \"Model for heat conduction in vaporizable endoskeletal droplet in response to x-ray photon absorption.\" Accepted for oral presentation on 4/2/23. Link to conference website: https://sb3c.org/" },
  { id: 7, text: "A Santoso, O Blasi, R Popple, S Holmes, K Woods, Y Vinogradskiy, A Qureshi, C Antonakakis, J Jones, DH Thomas, L Olsen, \"Multi-Institutional Study to Demonstrate An Increase in Variability of Delivered Dose to Patients for SRS Treatments as a Result of Dosimetric Leaf Gap Parameter Tuning\", AAPM 2022." },
  { id: 8, text: "DH Thomas, F Forghani, A Mahl, B Jones, M Borden, M Miften (2020), A fast and effective denoising solution using deep learning for real time X-ray Acoustic Computed Tomography Bulletin of the American Physical Society 65." },
  { id: 9, text: "F Forghani, A Mahl, B Jones, M Borden, M Miften, DH Thomas (2020), Analysis of experimental acoustic waves induced by high energy pulsed X-ray beams, Bulletin of the American Physical Society 65." },
  { id: 10, text: "F Forghani, A Mahl, G Shakya, M Borden, T Patton, Y Vinogradskiy, B Jones, M Miften, DH Thomas, (2020), Effect of X-Ray Irradiation On the Ultrasound Imaging Signal of a Novel Photoacoustic Contrast Agent, AAPM," },
  { id: 11, text: "M Lauria, D O'Connell , N Agazaryan , J Lewis , J Lamb , DH Thomas, P Lee, D Low (2019), Clinical Introduction of 5DCT Simulation for Lung Cancer, AAPM." },
  { id: 12, text: "F Forghani, DH Thomas (2019), An Analysis of X-Ray Induced Acoustic Imaging and Its Accuracy for Absolute Dosimetry, AAPM." },
  { id: 13, text: "T Patton, Q Diot , B Jones , L Olsen , Y Vinogradskiy , K Goodman , T Schefter , DH Thomas (2019), An Efficient Workflow for Generation and Refinement of a Knowledge Based Planning Model for Pancreas SBRT Using Automation, AAPM." },
  { id: 14, text: "J Ginn, D O'Connell , DH Thomas, D Low, J Lamb (2018), Model-Interpolated Gating for MRI- Guided Radiotherapy, AAPM." },
  { id: 15, text: "D O'Connell, DH Thomas, J Lewis , N Agazaryan , M Cao , S Tenn , P Lee , D Low (2018), Safety- Oriented Design of In-House Software for Translating New Techniques From Research to Clinical Practice: A Case Study Using a Model-Based 4DCT Protocol, , AAPM." },
  { id: 16, text: "D Low, D O'Connell , DH Thomas , T Dou , J Lewis , P Lee (2018), Is There a Better Way Than 4DCT to Characterize Breathing Motion, AAPM." },
  { id: 17, text: "J Ginn1, D O'Connell, DH Thomas , N Agazaryan , M Cao , Y Yang , D Low , J Lamb (2017), A Preliminary Evaluation of Respiratory Motion Modeling at 0.35T for MRI-Guided Radiotherapy, Medical Physics, TU-FG-FS2-2." },
  { id: 18, text: "D O'Connell, G Chee , J Lewis , DH Thomas , L Yang , P Lee , D Low (2017) Breathing Motion Model Estimation From Deformable Registration of CBCT Projections, , Medical Physics , MO-F- 205-5." },
  { id: 19, text: "DH Thomas*, W Campbell , J Faught , B Jones , K Goodman , M Miften (2017) 'Pseudo-4D' Localizer Radiographs: A Novel Imaging Technique for Evaluating the Motion of Implanted Fiducial Markers at Simulation, , Medical Physics, SU-E-601-8" },
  { id: 20, text: "O'Connell, D., N. Shaverdian, A. Kishan, D.H. Thomas, L. Yang, J. Lewis, J. Lamb, M. Cao, S. Tenn and P. Lee (2016). \"Clinical Validation and Implementation of the 5DCT Technique for Breathing- Gated Image Generation for Lung Cancer Treatment Planning.\" International Journal of Radiation Oncologyo Biologyo Physics 96(2): E687." },
  { id: 21, text: "Niedzielski, J., M. Miften, B. Jones, K. Goodman and D.H. Thomas (2017). \"Analysis of Acquisition Parameters and Pharmacokinetic Models From DCE-CT with Application to Outcome Assessment of Radiation Therapy: SU-K-601-15.\" Medical Physics 44(6)." },
  { id: 22, text: "Miller, B., T. Alexeev, D.H Thomas, K. Stuhr, B. Kavanagh, M. Miften and C. Altunbas (2018). CBCT-Based Dose Calculations with a Two-Dimensional Anti-Scatter Grid Prototype: The Effect of Scatter Suppression On Dose-Calculation Accuracy. MEDICAL PHYSICS, WILEY 111 RIVER ST, HOBOKEN 07030-5774, NJ USA." },
  { id: 23, text: "Low, D., D. O'Connell, D.H Thomas, T. Dou, J. Lewis and P. Lee (2018). Is There a Better Way Than 4DCT to Characterize Breathing Motion MEDICAL PHYSICS, WILEY 111 RIVER ST, HOBOKEN 07030-5774, NJ USA." },
  { id: 24, text: "Lee, P., M. Cao, J. Lamb, D.H. Thomas, A. Mikaeilian, M. Kamrava, J. Hernandez, N. Agazaryan, D. Low and M. Steinberg (2017). \"Phase 1 Study of Stereotactic Body Radiation Therapy for Liver Tumors Utilizing an MRI-Guided Tri-Co Teletherapy System.\" International Journal of Radiation Oncologyo Biologyo Physics 99(2): E164-E165." },
  { id: 25, text: "Lauria, M., D. O'Connell, N. Agazaryan, J. Lewis, J. Lamb, D.H Thomas, P. Lee and D. Low (2019). Clinical Introduction of 5DCT Simulation for Lung Cancer. MEDICAL PHYSICS, WILEY 111 RIVER ST, HOBOKEN 07030-5774, NJ USA." },
  { id: 26, text: "Lamb, J., J. Ginn, D. O'Connell, D.H Thomas, N. Agazaryan, M. Cao, Y. Yang and D. Low (2016). \"SUFJ151: Evaluation of a Magnetic Resonance Image Gated Radiotherapy System Using a Motion Phantom and Radiochromic Film.\" Medical physics 43(6Part11): 3442-3442." },
  { id: 27, text: "Ginn, J. S., D. O'Connell, D. H. Thomas, D. A. Low and J. M. Lamb (2018). \"Model-Interpolated Gating for Magnetic Resonance Image-Guided Radiation Therapy.\" International Journal of Radiation Oncology* Biology* Physics 102(4): 885-894." },
  { id: 28, text: "Ginn, J., D. O'connell, D. Thomas, N. Agazaryan, M. Cao, Y. Yang, D. Low and J. Lamb (2017). \"a Preliminary Evaluation of Respiratory Motion Modeling at 0.35 t for Mri-guided Radiotherapy: tu-fg- fs2-02.\" Medical Physics 44(6): 3155." },
  { id: 29, text: "Forghani, F. and D. Thomas (2019). An Analysis of X-Ray Induced Acoustic Imaging and Its Accuracy for Absolute Dosimetry. MEDICAL PHYSICS," },
  { id: 30, text: "Forghani, F., A. Mahl, B. Jones, M. Borden, M. Miften and D. Thomas (2020). \"Analysis of experimental acoustic waves induced by high energy pulsed X-ray beams.\" Bulletin of the American Physical Society 65." },
  { id: 31, text: "Faught, J., Y . Vinogradskiy, D. Thomas, M. Miften and D. Westerly (2017). \"Investigation of VMAT QA Discrepancies Observed with a Deterministic Dose Calculation Algorithm and Commercial Diode Array: TH-AB-FS1-10.\" Medical Physics 44(6)." },
  { id: 32, text: "Campbell, W., D. Thomas, M. Miften and B. Jones (2017). \"Masking for Gold: Automated Segmentation of Arbitrarily-Shaped Fiducial Markers in Cone-Beam CT Projections and Pseudo-4D Topograms: TU-H-CAMPUS-JT-03.\" Medical Physics 44(6): 3178-3179." },
  { id: 33, text: "Yang Y, Cao M, Sheng K, ...,Thomas DH, et al. Longitudinal diffusion MRI for treatment response assessment: Preliminary experience using an MRI-guided tri-cobalt 60 radiotherapy system. Medical physics. 2016;43(3):1369-1373." },
  { id: 34, text: "Yang Y, Cao M, Kamrava M, ...,Thomas DH, et al. WEFG20211: Longitudinal Diffusion MRI for Treatment Assessment of Sarcoma Patients with PreOperative Radiation Therapy. Medical physics. 2016;43(6):3829-3829." },
  { id: 35, text: "Yang L, O'Connell D, Lee P,..., Thomas DH, et al. SUFJ135: Tumor DisplacementBased Binning for RespiratoryGated TimeIndependent 5DCT Treatment Planning. Medical physics. 2016;43(6):3438-3438." },
  { id: 36, text: "Thomas DH, Kishan A, Santhanam A, et al. SUGBRA04: Simulation of Errors in Maximal Intensity Projection (MIP)Based Lung Tumor Internal Target Volumes (ITV) Using RealTime 2D MRI and Deformable Image Registration Based Lung Tumor Tracking. Medical physics. 2016;43(6):3635- 3636." },
  { id: 37, text: "Rwigema J, Thomas DH, Cao M, Yoshizaki T, Chen A. Intrafraction Organ Motion Tracking With Real-Time MRI-Guided Radiation Therapy for Head and Neck Cancer. International Journal of Radiation Oncologyo Biologyo Physics. 2016;94(4):878." },
  { id: 38, text: "O'Connell D, Shaverdian N, Kishan A, Thomas, DH et al. Clinical Validation and Implementation of the 5DCT Technique for Breathing-Gated Image Generation for Lung Cancer Treatment Planning. International journal of radiation oncology, biology, physics. 2016;96(2S):E687." },
  { id: 39, text: "O'Connell D, Thomas DH, Dou T, et al. SUD20206: Prospective FreeBreathing CT Scan Selection for 5DCT. Medical physics. 2016;43(6):3342-3342." },
  { id: 40, text: "Nguyen D, Thomas DH, Cao M, O'Connor D, Lamb J, Sheng K. TH-AB-BRA-02: Automated Triplet Beam Orientation Optimization for MRI-Guided Co-60 Radiotherapy. Medical Physics. 2016;43(6):3853-3854." },
  { id: 41, text: "Low D, Thomas DH, Dou T, Lee P, Lewis J, O'Connell D. PO-0880: Clinical implementation of 5DCT workflow. Radiotherapy and Oncology. 2016;119:S422." },
  { id: 42, text: "Lamb J, Ginn J, O'Connell D, DH Thomas et al. SUFJ151: Evaluation of a Magnetic Resonance Image Gated Radiotherapy System Using a Motion Phantom and Radiochromic Film. Medical physics. 2016;43(6):3442-3442." },
  { id: 43, text: "Kamrava M, Agazaryan N, Cao M, DH Thomas et al. Assessment of Intrafraction Motion of the Vaginal Apex During Postoperative MRI-Guided Radiation Therapy. International Journal of Radiation Oncologyo Biologyo Physics. 2016;96(2):E302." },
  { id: 44, text: "Dou TH, Min Y, Neylon J, Thomas DH, Kupelian P, Santhanam AP. Fast simulated annealing and adaptive Monte Carlo sampling based parameter optimization for dense optical-flow deformable image registration of 4DCT lung anatomy. Paper presented at: SPIE Medical Imaging2016." },
  { id: 45, text: "Chow P, Thomas DH, Agazaryan N, et al. SU-FJ-125: Effects of Couch Position Variability On Dosimetric Accuracy with An MRI-Guided Co-60 Radiation Therapy Machine. Medical Physics. 2016;43(6):3435-3436." },
  { id: 46, text: "Yang Y, Low D, Cao M, et al. TH-CD-204-06: Diffusion MRI for Treatment Response Assessment of MRI-Guided Tri-Cobalt 60 Radiotherapy. Medical physics. 2015;42(6):3733-3733." },
  { id: 47, text: "Yang LL, O'Connell D, Dou T, Thomas DH, Lamb J, Low DA. SU-EJ-156: Velocity-Based Reference Scan Selection for Motion-Model Error Reduction of 5DCT. Medical physics. 2015;42(6):3300-3300." },
  { id: 48, text: "Yang LL, Dou T, O'Connell D, DH Thomas et al. TU-F-CAMPUS-J-05: Quantitative Evaluation of the Relationship Between Tissue Velocity and Motion-Artifacts of Free-Breathing Low-Dose Fast- Helical CT Scans. Medical physics. 2015;42(6):3646-3646." },
  { id: 49, text: "Thomas DH, O'Connell D, Lamb J, et al. SU-F-303-17: Real Time Dose Calculation of MRI Guided Co-60 Radiotherapy Treatments On Free Breathing Patients, Using a Motion Model and Fast Monte Carlo Dose Calculation. Medical physics. 2015;42(6):3541-3541." },
  { id: 50, text: "Santhanam A, Seyfi B, Thomas DH, Ilegbusi O. TH-CD-303-01: On Characterizing 4D Lung Motion Using Coupled Multi-Physics Framework of Computational Fluid Dynamics, Linear Elasticity Estimation and 4D Lung Deformable Image Registration. Medical physics. 2015;42(6):3728-3728." },
  { id: 51, text: "Ruan D, Dou T, Thomas DH, Low D. MO-FG-204-02: Reference Image Selection in the Presence of Multiple Scan Realizations. Medical physics. 2015;42(6):3569-3569." },
  { id: 52, text: "O'Connell D, Thomas DH, Kishan A, et al. Generation of Lung Tumor Internal Target Volumes (ITV) Using A Novel Breathing Gated Imaging and Analysis Technique. International Journal of Radiation Oncologyo Biologyo Physics. 2015;93(3):E610." },
  { id: 53, text: "O'Connell D, Thomas DH, Dou T, Lamb J, Yang L, Low D. SU-C-BRA-05: Fast Generation of Respiratory Gated CT Images at User Selected Breathing Phases On a Graphics Processing Unit. Medical physics. 2015;42(6):3196-3196." },
  { id: 54, text: "O'Connell D, Thomas DH, Dou T, Lamb J, Yang L, Low D. SU-EJ-234: Application of a Breathing Motion Model to ViewRay Cine MR Images. Medical physics. 2015;42(6):3319-3319." },
  { id: 55, text: "Liu J, Gao Y, Thomas DH, et al. TH-CD-303-11: Simultaneous Reference-Image and Deformation- Field Reconstruction for 4DCBCT with Periodic and Non-Periodic Breathing Based On 5D Respiratory Motion Model. Medical physics. 2015;42(6):3731-3731." },
  { id: 56, text: "Lamb J, Kamrava M, Agazaryan N, DH Thomas et al. SU-EJ-206: Adaptive Radiotherapy for Gynecological Malignancies with MRIGuided Cobolt-60 Radiotherapy. Medical physics. 2015;42(6):3312-3313." },
  { id: 57, text: "Lamb J, Agazaryan N, Cao M, Low D, Thomas DH, Yang Y. SU-EJ-198: Out-Of-Field Dose and Surface Dose Measurements of MRI-Guided Cobalt-60 Radiotherapy. Medical physics. 2015;42(6):3310-3311." },
  { id: 58, text: "Dou T, Thomas DH, O'Connell D, Lamb J, Low D. TH-CD-303-04: A Method for Assessing Ground- Truth Accuracy of a Motion Model Based 4DCT Technique. Medical physics. 2015;42(6):3729-3729." },
  { id: 59, text: "Dermitzakis A, Butler MB, Thomas DH, Sboros V. The polydisperse acoustic signature of rigid microbubbles. Paper presented at: Engineering in Medicine and Biology Society (EMBC), 2015 37th Annual International Conference of the IEEE2015." },
  { id: 60, text: "Thomas DH, Tan J, Neylon J, et al. TH-C-18A-11: Investigating the Minimum Scan Parameters Required to Generate Free-Breathing Fast-Helical CT Scans Without Motion-Artifacts. Medical Physics. 2014;41(6):559-559." },
  { id: 61, text: "Perperidis A, Thomas DH, Averkiou M, et al. Automatic dissociation between microvasculature and larger vessels for ultrasound contrast imaging. Paper presented at: Engineering in Medicine and Biology Society (EMBC), 2014 36th Annual International Conference of the IEEE2014." },
  { id: 62, text: "Low D, Thomas DH, Lamb J, et al. OC-0501: Comparison between existing and proposed 4DCT protocols. Radiotherapy and Oncology. 2014;111:S196-S197." },
  { id: 63, text: "Gao Y, Thomas DH, Low D, Gao H. SU-D-17A-03: 5D Respiratory Motion Model Based Iterative Reconstruction Method for 4D Cone-Beam CT. Medical Physics. 2014;41(6):117-117." },
  { id: 64, text: "Dou T, Thomas DH, Lamb J, Low D. SU-D-17A-05: A Method to Determine the Accuracy of a Proposed Breathing Motion Model-Based 4DCT Technique. Medical Physics. 2014;41(6):117-117." },
  { id: 65, text: "Dou T, Thomas DH, Lamb J, Low D. SU-EJ-25: Analysis of Commercial 4DCT Flaws and the Potential Benefits of a New Technique for Irregular Breathing Patients. Medical Physics. 2014;41(6):160-160." },
  { id: 66, text: "Butler MB, Dermitzakis A, Looney P, Thomas DH, Pye SD, Sboros V. A setup for the assessment of the effect of tubular confinement on the acoustic response of microbubbles. Paper presented at: Engineering in Medicine and Biology Society (EMBC), 2014 36th Annual International Conference of the IEEE2014." },
  { id: 67, text: "White B, Thomas DH, Lamb J, et al. WEA13408: Modeling Cardiac Induced Lung Tissue Motion for a Quantitative Breathing Motion Model. Medical Physics. 2013;40(6):470-471." },
  { id: 68, text: "Thomas DH, Sboros V, Emmer M, Vos H, De Jong N. Microbubble oscillations in capillary tubes. IEEE transactions on ultrasonics, ferroelectrics, and frequency control. 2013;60(1)." },
  { id: 69, text: "Thomas DH, White B, Gaudio S, et al. TUG14101: BEST IN PHYSICS (JOINT IMAGINGTHERAPY)A Novel 4D CT Acquisition and Analysis Technique to Generate Low Noise Artifact Free Images at User Selected Breathing Phases. Medical Physics. 2013;40(6):456-456." },
  { id: 70, text: "Thomas DH, White B, Gaudio S, et al. MOFWAB07: A Novel 4D CT Acquisition and Analysis Technique to Account for the Effect of Cardiac Induced Lung Tissue Motion During Free Breathing. Medical Physics. 2013;40(6):411-411." },
  { id: 71, text: "Low D, Thomas DH, White B, et al. SUEJ126: Development of a Prospective Gating Algorithm for a Novel 4DCT Technique: Retrospective Data Analysis. Medical Physics. 2013;40(6):179-179." },
  { id: 72, text: "Low D, Lamb J, White B, ...,Thomas DH, et al.. A New 4DCT Technique. International Journal of Radiation Oncology* Biology* Physics. 2013;87(2):S671-S672." },
  { id: 73, text: "Low D, Lamb J, Lee P, Thomas DH, White B. OC-0058: A novel 4DCT technique for breathing motion modeling. Radiotherapy and Oncology. 2013;106:S22." },
  { id: 74, text: "Lamb J, Jani S, White B, ...,Thomas DH, et al.. SUEJ82: GroundTruth Tests of Deformable Image Registration Using Matched PETCT Image Pairs. Medical Physics. 2013;40(6):169-169." },
  { id: 75, text: "Jani S, Dahlbom M, White B, ...,Thomas DH, et al.. SUD50005: Comparison of Gating Algorithms in 4DPET for Mobile Tumor Segmentation. Medical Physics. 2013;40(6):106-106." },
  { id: 76, text: "Gaudio S, Thomas DH, White B, et al. SUEJ138: Breathing Motion Model Comparison Inside and Outside the Lung. Medical Physics. 2013;40(6):182-182." },
  { id: 77, text: "Aliotta E, Thomas DH, Gaudio S, et al. TUC14106: Improving Image Quality in 4DCT Scans Using Deformable Registration and Selective Averaging. Medical Physics. 2013;40(6):434-435." },
  { id: 78, text: "Thomas DH, Butler M, Looney P, Pelekasis N, Sboros V. The effect of resonance on transient microbubble response; response; experimental and theoretical observations. Paper presented at: Ultrasonics Symposium (IUS), 2012 IEEE International2012." },
  { id: 79, text: "Thomas DH, Looney P, Butler M, et al. The fate of resonant and off-resonant microbubble signals in response to consecutive imaging pulses. Paper presented at: Ultrasonics Symposium (IUS), 2010 IEEE2010." },
  { id: 80, text: "Butler MB, Dermitzakis A, Thomas DH, Looney P, Pye S, Sboros V. Single microbubble acoustics in small tubes. Paper presented at: Proc Int Conf Acoust2010." },
  { id: 81, text: "Thomas DH, Sboros V, Emmer M, Vos HJ, de Jong N. Optical observations of microbubble oscillation in small tubes. Paper presented at: Ultrasonics Symposium (IUS), 2009 IEEE International2009." },
  { id: 82, text: "Looney P, Thomas DH, Steel R, Anderson T, Pelekasis N, Sboros V. A new theoretical model for cracked microbubbles. Paper presented at: Ultrasonics Symposium (IUS), 2009 IEEE International2009." },
  { id: 83, text: "Butler MB, Zhang A, Thomas DH, et al. 0363: Acoustic Investigation of Attached, Single Microbubbles. Ultrasound in Medicine & Biology. 2009;35(8):S50." },
  { id: 84, text: "Butler M, Dermitzakis A, Thomas DH, Pye SD, Sboros V. Survival of single microbubbles insonated in solution and in narrow tubes. Paper presented at: Ultrasonics Symposium (IUS), 2009 IEEE International2009." },
  { id: 85, text: "Looney P, Thomas DH, Steel R, Anderson T, Pelekasis N, Sboros V. A realistic model for ultrasound contrast microbubbles: initial results. Paper presented at: WIMRC Cavitation Forum2008." },
  { id: 86, text: "Butler M, Thomas DH, Moran C, McDicken W, Sboros V, Pye S. Comparison of the acoustic response of attached and unattached BiSphereTM microbubbles. Paper presented at: Ultrasonics Symposium, 2008. IUS 2008. IEEE2008." },
  { id: 87, text: "Thomas DH, Butler M, Anderson T, McDicken W, Sboros V. P5B-10 Single Microbubble Acoustics with Signal Processing: Initial Experience with Amplitude Modulated Pulse Sequences. Paper presented at: Ultrasonics Symposium, 2007. IEEE2007." },
]
