export interface Publication {
  title: string
  authors: string
  journal?: string
  publisher?: string
  year: string
  volume?: string
  pages?: string
  url?: string
  tags?: string[]
  citations?: number
}

export const publications: Publication[] = [
  // Recent publications first
  {
    title:
      "2D antiscatter grid and scatter sampling based CBCT method for online dose calculations during CBCT guided radiation therapy of pelvis",
    authors: "F Bayat, B Miller, Y Park, Z Yu, T Alexeev, D Thomas, K Stuhr, M Miften, C Altunbas",
    journal: "Medical Physics",
    year: "2023",
    citations: 4,
    tags: ["CBCT", "Dose Calculation", "Radiation Therapy"],
  },
  {
    title: "Computer Vision assisted Collision Avoidance for Radiation Therapy",
    authors: "David Thomas, Moyed Miften, Brian Kavanagh, Bernard Trip Jones",
    year: "2023",
    url: "https://whova.com/portal/webapp/arsan_202305/...",
    tags: ["Computer Vision", "Collision Avoidance"],
  },
  {
    title:
      "Multi-Institutional Study to Demonstrate An Increase in Variability of Delivered Dose to Patients for SRS Treatments as a Result of Dosimetric Leaf Gap Parameter Tuning",
    authors: "A Santoso, O Blasi, R Popple, S Holmes, K Woods, Y Vinogradskiy, D Thomas",
    journal: "MEDICAL PHYSICS",
    volume: "49 (6)",
    pages: "E361-E361",
    year: "2022",
    tags: ["SRS", "Dosimetry", "Treatment Planning"],
  },
  {
    title:
      "Characterizing spatial differences between SPECT-ventilation and SPECT-perfusion in patients with lung cancer undergoing radiotherapy",
    authors:
      "Farnoush Forghani, Taylor Patton, Jennifer Kwak, David Thomas, Quentin Diot, Chad Rusthoven, Richard Castillo, Edward Castillo, Inga Grills, Thomas Guerrero, others",
    journal: "Radiotherapy and Oncology",
    volume: "160",
    publisher: "Elsevier",
    year: "2021",
    pages: "120--124",
    citations: 10,
    tags: ["SPECT", "Lung Cancer", "Radiotherapy"],
  },
  {
    title:
      "Simulation of x-ray-induced acoustic imaging for absolute dosimetry: Accuracy of image reconstruction methods",
    authors:
      "Farnoush Forghani, Adam Mahl, Taylor J Patton, Bernard L Jones, Mark A Borden, David C Westerly, Cem Altunbas, Moyed Miften, David H Thomas",
    journal: "Medical Physics",
    volume: "47",
    publisher: "Wiley Online Library",
    year: "2020",
    pages: "1280--1290",
    citations: 25,
    tags: ["X-ray", "Acoustic Imaging", "Dosimetry"],
  },
  {
    title:
      "Deep Learning approach for automatic detection and identification of patient positioning devices for radiation therapy",
    authors:
      "David H Thomas, Leah K Schubert, Yevgeniy Vinogradskiy, Sameer Nath, Brian Kavanagh, Moyed Miften, Bernard Jones",
    journal: "Medical Physics",
    publisher: "Wiley Online Library",
    year: "2020",
    tags: ["Deep Learning", "Patient Positioning", "Radiation Therapy"],
  },
  {
    title:
      "Integration of automation into an existing clinical workflow to improve efficiency and reduce errors in the manual treatment planning process for total body irradiation (TBI)",
    authors:
      "David H Thomas, Brian Miller, Rachel Rabinovitch, Sarah Milgrom, Brian Kavanagh, Quentin Diot, Moyed Miften, Leah K Schubert",
    journal: "Journal of Applied Clinical Medical Physics",
    publisher: "Wiley Online Library",
    year: "2020",
    citations: 4,
    tags: ["Automation", "Treatment Planning", "TBI"],
  },
  {
    title: "Effect of X-Ray Irradiation On the Ultrasound Imaging Signal of a Novel Photoacoustic Contrast Agent",
    authors: "F Forghani, A Mahl, G Shakya, M Borden, T Patton, Y Vinogradskiy, B Jones, M Miften, D Thomas",
    journal: "MEDICAL PHYSICS",
    volume: "47",
    publisher: "WILEY 111 RIVER ST, HOBOKEN 07030-5774, NJ USA",
    year: "2020",
    pages: "E763--E763",
    tags: ["X-ray", "Ultrasound", "Photoacoustic"],
  },
  {
    title:
      "Lung Functional Avoidance Radiotherapy: Characterizing Spatial Differences Between Ventilation and Perfusion",
    authors:
      "F Forghani, T Patton, D Thomas, Q Diot, C Rusthoven, R Castillo, E Castillo, I Grills, T Guerrero, M Miften, others",
    journal: "MEDICAL PHYSICS",
    volume: "47",
    publisher: "WILEY 111 RIVER ST, HOBOKEN 07030-5774, NJ USA",
    year: "2020",
    pages: "E370--E370",
    tags: ["Lung", "Radiotherapy", "Ventilation"],
  },
  {
    title: "Analysis of experimental acoustic waves induced by high energy pulsed X-ray beams",
    authors: "Farnoush Forghani, Adam Mahl, Bernard Jones, Mark Borden, Moyed Miften, David Thomas",
    journal: "Bulletin of the American Physical Society",
    volume: "65",
    publisher: "APS",
    year: "2020",
    tags: ["X-ray", "Acoustic Waves"],
  },
  {
    title:
      "A fast and effective denoising solution using deep learning for real time X-ray Acoustic Computed Tomography",
    authors: "David Thomas, Farnoush Forghani, Adam Mahl, Bernard Jones, Mark Borden, Moyed Miften",
    journal: "Bulletin of the American Physical Society",
    volume: "65",
    publisher: "APS",
    year: "2020",
    tags: ["Deep Learning", "X-ray", "Acoustic CT"],
  },
  {
    title: "The current state of physics plan review training in medical physics residency programs in North America",
    authors:
      "Leah K Schubert, Kristi Hendrickson, Moyed Miften, Monica McNulty, Yevgeniy Y Vinogradskiy, David H Thomas, David Westerly, Kelly Stuhr, Janet Corral, Danielle Royer",
    journal: "Practical radiation oncology",
    publisher: "Elsevier",
    year: "2019",
    citations: 6,
    tags: ["Medical Physics", "Education", "Plan Review"],
  },
  {
    title:
      "Safety-oriented design of in-house software for new techniques: A case study using a model-based 4 DCT protocol",
    authors:
      "Dylan O'Connell, David H Thomas, John H Lewis, Katelyn Hasse, Anand Santhanam, James M Lamb, Minsong Cao, Stephen Tenn, Nzhde Agazaryan, Percy P Lee, others",
    journal: "Medical physics",
    volume: "46",
    publisher: "Wiley Online Library",
    year: "2019",
    pages: "1523--1532",
    citations: 3,
    tags: ["Software Design", "4DCT", "Safety"],
  },
  {
    title: "An Analysis of X-Ray Induced Acoustic Imaging and Its Accuracy for Absolute Dosimetry",
    authors: "F Forghani, D Thomas",
    journal: "MEDICAL PHYSICS",
    volume: "46",
    publisher: "WILEY 111 RIVER ST, HOBOKEN 07030-5774, NJ USA",
    year: "2019",
    pages: "E412--E413",
    tags: ["X-ray", "Acoustic Imaging", "Dosimetry"],
  },
  {
    title: "Clinical Introduction of 5DCT Simulation for Lung Cancer",
    authors: "M Lauria, D O'Connell, N Agazaryan, J Lewis, J Lamb, D Thomas, P Lee, D Low",
    journal: "MEDICAL PHYSICS",
    volume: "46",
    publisher: "WILEY 111 RIVER ST, HOBOKEN 07030-5774, NJ USA",
    year: "2019",
    pages: "E521--E522",
    tags: ["5DCT", "Lung Cancer", "Simulation"],
  },
  {
    title:
      "An Efficient Workflow for Generation and Refinement of a Knowledge Based Planning Model for Pancreas SBRT Using Automation",
    authors: "T Patton, Q Diot, B Jones, L Olsen, Y Vinogradskiy, K Goodman, T Schefter, D Thomas",
    journal: "MEDICAL PHYSICS",
    volume: "46",
    publisher: "WILEY 111 RIVER ST, HOBOKEN 07030-5774, NJ USA",
    year: "2019",
    pages: "E367--E367",
    tags: ["Knowledge Based Planning", "Pancreas", "SBRT"],
  },
  {
    title: "Initial clinical observations of intra-and interfractional motion variation in MR-guided lung SBRT",
    authors: "DH Thomas, A Santhanam, AU Kishan, M Cao, J Lamb, Y Min, D O'Connell, Y Yang, N Agazaryan, PP Lee",
    journal: "The British journal of radiology",
    volume: "91",
    year: "2018",
    pages: "20170522",
    citations: 66,
    tags: ["MR-guided", "Lung SBRT", "Motion Variation"],
  },
  {
    title:
      "The effect of resonance on transient microbubble acoustic response: Experimental observations and numerical simulations",
    authors: "K Efthymiou, N Pelekasis, MB Butler, DH Thomas, V Sboros",
    journal: "The Journal of the Acoustical Society of America",
    volume: "143",
    publisher: "ASA",
    year: "2018",
    pages: "1392--1406",
    citations: 12,
    tags: ["Microbubble", "Acoustics", "Simulation"],
  },
  {
    title: "Model-Interpolated Gating for Magnetic Resonance Image–Guided Radiation Therapy",
    authors: "JS Ginn, D O'Connell, DH Thomas, DA Low, JM Lamb",
    journal: "International Journal of Radiation Oncology* Biology* Physics",
    volume: "102",
    year: "2018",
    pages: "885-894",
    citations: 15,
    tags: ["MRI-guided", "Radiation Therapy", "Gating"],
  },
  {
    title:
      "Dependence of subject-specific parameters for a fast helical CT respiratory motion model on breathing rate: an animal study",
    authors: "D O'Connell, DH Thomas, JM Lamb, JH Lewis, T Dou, JP Sieren, DA Low",
    journal: "Physics in Medicine & Biology",
    volume: "63",
    year: "2018",
    pages: "04NT04",
    citations: 4,
    tags: ["CT", "Respiratory Motion", "Animal Study"],
  },
  {
    title:
      "A generalized framework unifying image registration and respiratory motion models and incorporating image reconstruction, for partial image data or full images",
    authors:
      "JR McClelland, M Modat, S Arridge, H Grimes, D D'Souza, D Thomas, D O'Connell, DA Low, E Kaza, DJ Collins",
    journal: "Physics in Medicine & Biology",
    volume: "62",
    year: "2017",
    pages: "4273",
    citations: 66,
    tags: ["Image Registration", "Respiratory Motion", "Image Reconstruction"],
  },
  {
    title:
      "Feasibility evaluation of diffusion-weighted imaging using an integrated MRI-radiotherapy system for response assessment to neoadjuvant therapy in rectal cancer",
    authors: "N Shaverdian, Y Yang, P Hu, S Hart, K Sheng, J Lamb, M Cao, DH Thomas, Y Gao, M Kamrava",
    journal: "The British journal of radiology",
    volume: "90",
    year: "2017",
    pages: "20160739",
    citations: 58,
    tags: ["Diffusion-weighted Imaging", "MRI", "Rectal Cancer"],
  },
  {
    title:
      "Dosimetric validation of a magnetic resonance image gated radiotherapy system using a motion phantom and radiochromic film",
    authors: "JM Lamb, JS Ginn, DP O'Connell, N Agazaryan, M Cao, DH Thomas, Y Yang, DA Low, PP Lee",
    journal: "Journal of Applied Clinical Medical Physics",
    volume: "18",
    year: "2017",
    pages: "163-169",
    citations: 49,
    tags: ["MRI", "Radiotherapy", "Dosimetry"],
  },
  {
    title: "Adaptive weighted median filtering for reduced blurring when fusing co-registered fast helical CT images",
    authors: "D O'Connell, DH Thomas, TH Dou, E Aliotta, JH Lewis, JM Lamb, P Lee, DA Low",
    journal: "Biomedical Physics & Engineering Express",
    volume: "3",
    year: "2017",
    pages: "067002",
    citations: 7,
    tags: ["CT", "Image Fusion", "Filtering"],
  },
  {
    title: "Analysis of motion blurring artifact in fast helical free‐breathing thoracic CT scans",
    authors: "DA Low, L Yang, J Chen, D O'Connel, JH Lewis, DH Thomas, P Lee",
    journal: "Medical Physics",
    volume: "44",
    year: "2017",
    pages: "1456-1461",
    citations: 9,
    tags: ["CT", "Motion Artifact", "Thoracic Imaging"],
  },
  {
    title: "Online Adaptive Radiation Therapy: Implementation of a New Process of Care",
    authors:
      "J Lamb, M Cao, A Kishan, N Agazaryan, DH Thomas, N Shaverdian, Y Yang, S Ray, DA Low, JD Steinberg, PP Lee",
    journal: "Cureus",
    volume: "9",
    year: "2017",
    pages: "e1618",
    citations: 138,
    tags: ["Adaptive Radiation Therapy", "Process of Care", "Implementation"],
  },
  {
    title: "Comparison of lung tumor motion measured using a model-based 4DCT technique and a commercial protocol",
    authors: "D O'Connell, N Shaverdian, AU Kishan, DH Thomas, TH Dou, JH Lewis, DA Low, PP Lee",
    journal: "Practical Radiation Oncology",
    year: "2017",
    citations: 11,
    tags: ["Lung Tumor", "Motion", "4DCT"],
  },
  {
    title:
      "Longitudinal diffusion MRI for treatment response assessment: Preliminary experience using an MRI-guided tri-cobalt 60 radiotherapy system",
    authors: "Y Yang, M Cao, K Sheng, Y Gao, A Chen, M Kamrava, P Lee, DH Thomas, DA Low, PP Hu",
    journal: "Medical physics",
    volume: "43",
    year: "2016",
    pages: "1369-1373",
    citations: 124,
    tags: ["Diffusion MRI", "Treatment Response", "Radiotherapy"],
  },
  {
    title: "Is there an ideal set of prospective scan acquisition phases for fast-helical based 4D-CT?",
    authors: "DH Thomas, D Ruan, P Williams, J Lamb, BM White, T Dou, D O'Connell, JH Lewis, DA Low",
    journal: "Physics in Medicine & Biology",
    volume: "61",
    year: "2016",
    pages: "N632",
    citations: 9,
    tags: ["4D-CT", "Scan Acquisition", "Fast-helical"],
  },
  {
    title: "Computerized triplet beam orientation optimization for MRI‐guided Co‐60 radiotherapy",
    authors: "D Nguyen, D Thomas, M Cao, D O'Connor, J Lamb, K Sheng",
    journal: "Medical physics",
    volume: "43",
    year: "2016",
    pages: "5667-5675",
    citations: 19,
    tags: ["Beam Orientation", "Optimization", "MRI-guided"],
  },
  {
    title:
      "Fast simulated annealing and adaptive Monte Carlo sampling based parameter optimization for dense optical-flow deformable image registration of 4DCT lung anatomy",
    authors: "TH Dou, Y Min, J Neylon, D Thomas, P Kupelian, AP Santhanam",
    journal: "Medical Imaging 2016: Image-Guided Procedures, Robotic Interventions, and Modeling",
    volume: "9786",
    year: "2016",
    citations: 11,
    tags: ["Parameter Optimization", "Image Registration", "4DCT"],
  },
  {
    title: "Intrafraction Organ Motion Tracking With Real-Time MRI-Guided Radiation Therapy for Head and Neck Cancer",
    authors: "JC Rwigema, DH Thomas, M Cao, T Yoshizaki, AM Chen",
    journal: "International Journal of Radiation Oncology• Biology• Physics",
    volume: "94",
    year: "2016",
    pages: "878",
    citations: 2,
    tags: ["Organ Motion", "MRI-guided", "Head and Neck Cancer"],
  },
  {
    title:
      "Dosimetric effects of couch position variability on treatment plan quality with an MRI‐guided Co‐60 radiation therapy machine",
    authors: "PE Chow, DH Thomas, N Agazaryan, M Cao, DA Low, Y Yang, JM Lamb",
    journal: "Medical physics",
    volume: "43",
    year: "2016",
    pages: "4514-4519",
    citations: 1,
    tags: ["Couch Position", "MRI-guided", "Treatment Planning"],
  },
  {
    title: "A Method for Assessing Ground-Truth Accuracy of the 5DCT Technique",
    authors: "TH Dou, DH Thomas, DP O'Connell, JM Lamb, P Lee, DA Low",
    journal: "International Journal of Radiation Oncology* Biology* Physics",
    volume: "93",
    year: "2015",
    pages: "925-933",
    citations: 34,
    tags: ["5DCT", "Ground-Truth", "Accuracy"],
  },
  {
    title: "5D respiratory motion model based image reconstruction algorithm for 4D cone-beam computed tomography",
    authors: "J Liu, X Zhang, X Zhang, H Zhao, Y Gao, D Thomas, DA Low, H Gao",
    journal: "Inverse Problems",
    volume: "31",
    year: "2015",
    pages: "115007",
    citations: 47,
    tags: ["Respiratory Motion", "Image Reconstruction", "CBCT"],
  },
  {
    title:
      "Comparison of breathing gated CT images generated using a 5DCT technique and a commercial clinical protocol in a porcine model",
    authors: "DP O'Connell, DH Thomas, TH Dou, JM Lamb, F Feingold, DA Low, PP Lee",
    journal: "Medical physics",
    volume: "42",
    year: "2015",
    pages: "4033-4042",
    citations: 20,
    tags: ["Breathing Gated CT", "5DCT", "Porcine Model"],
  },
  {
    title: "Simulation of 4DCT tumor motion measurement errors",
    authors: "TH Dou, DH Thomas, D O'Connell, JD Bradley, JM Lamb, DA Low",
    journal: "Medical physics",
    volume: "42",
    year: "2015",
    pages: "6084-6089",
    citations: 16,
    tags: ["4DCT", "Tumor Motion", "Simulation"],
  },
  {
    title: "Objective function to obtain multiple representative waveforms for a novel helical CT scan protocol",
    authors: "D Ruan, D Thomas, DA Low",
    journal: "Medical Physics",
    volume: "42",
    year: "2015",
    pages: "1164-1169",
    citations: 7,
    tags: ["Helical CT", "Waveforms", "Scan Protocol"],
  },
  {
    title:
      "A Novel Fast Helical 4D-CT Acquisition Technique to Generate Low-Noise Sorting Artifact–Free Images at User-Selected Breathing Phases",
    authors: "D Thomas, J Lamb, B White, S Jani, S Gaudio, P Lee, D Ruan, M McNitt-Gray, DA Low",
    journal: "International Journal of Radiation Oncology* Biology* Physics",
    volume: "89",
    year: "2014",
    pages: "191-198",
    citations: 78,
    tags: ["4D-CT", "Helical", "Breathing Phases"],
  },
  {
    title: "Modeling and incorporating cardiac‐induced lung tissue motion in a breathing motion model",
    authors: "BM White, A Santhanam, D Thomas, Y Min, JM Lamb, J Neylon, S Jani, S Gaudio, S Srinivasan, D Ennis",
    journal: "Medical physics",
    volume: "41",
    year: "2014",
    pages: "041701",
    citations: 9,
    tags: ["Cardiac-induced Motion", "Lung Tissue", "Motion Model"],
  },
  {
    title: "Automatic dissociation between microvasculature and larger vessels for ultrasound contrast imaging",
    authors: "A Perperidis, D Thomas, M Averkiou, C Duncan, A McNeilly, M Butler, V Sboros",
    journal:
      "Engineering in Medicine and Biology Society (EMBC), 2014 36th Annual International Conference of the IEEE",
    year: "2014",
    pages: "5076-5079",
    citations: 8,
    tags: ["Ultrasound", "Contrast Imaging", "Microvasculature"],
  },
  {
    title: "A novel CT acquisition and analysis technique for breathing motion modeling",
    authors: "DA Low, BM White, PP Lee, DH Thomas, S Gaudio, SS Jani, X Wu, D Lamb",
    journal: "Physics in Medicine & Biology",
    volume: "58",
    year: "2013",
    pages: "L31",
    citations: 68,
    tags: ["CT", "Breathing Motion", "Modeling"],
  },
  {
    title:
      "A Comparison of Amplitude-Based and Phase-Based Positron Emission Tomography Gating Algorithms for Segmentation of Internal Target Volumes of Tumors Subject to Respiratory Motion",
    authors: "SS Jani, CG Robinson, M Dahlbom, BM White, DH Thomas, S Gaudio, DA Low, JD Bradley, JM Lamb",
    journal: "International Journal of Radiation Oncology* Biology* Physics",
    volume: "87",
    year: "2013",
    pages: "562-569",
    citations: 30,
    tags: ["PET", "Gating", "Respiratory Motion"],
  },
  {
    title: "Microbubble oscillations in capillary tubes",
    authors: "DH Thomas, V Sboros, M Emmer, H Vos, N De Jong",
    journal: "IEEE transactions on ultrasonics, ferroelectrics, and frequency control",
    volume: "60",
    year: "2013",
    pages: "105-114",
    citations: 41,
    tags: ["Microbubble", "Oscillations", "Capillary Tubes"],
  },
  {
    title: "The acoustic signature of decaying resonant phospholipid microbubbles",
    authors: "DH Thomas, M Butler, N Pelekasis, T Anderson, E Stride, V Sboros",
    journal: "Physics in Medicine & Biology",
    volume: "58",
    year: "2013",
    pages: "589",
    citations: 12,
    tags: ["Acoustic", "Microbubbles", "Phospholipid"],
  },
  {
    title: 'The "quasi-stable" lipid shelled microbubble in response to consecutive ultrasound pulses',
    authors: "DH Thomas, M Butler, T Anderson, M Emmer, H Vos, M Borden, E Stride, N de Jong, V Sboros",
    journal: "Applied Physics Letters",
    volume: "101",
    year: "2012",
    pages: "071601",
    citations: 33,
    tags: ["Lipid", "Microbubble", "Ultrasound"],
  },
  {
    title: "Imaging of the ovine corpus luteum microcirculation with contrast ultrasound",
    authors: "V Sboros, M Averkiou, M Lampaskis, DH Thomas, N Silva, C Strouthos, CM Loizou, CL Pitsillides",
    journal: "Ultrasound in Medicine and Biology",
    volume: "37",
    year: "2011",
    pages: "59-68",
    citations: 24,
    tags: ["Ultrasound", "Contrast", "Microcirculation"],
  },
  {
    title: "On the acoustic response of microbubbles in arteriole sized vessels",
    authors: "MB Butler, DH Thomas, N Silva, SD Pye, V Sboros",
    journal: "Applied Physics Letters",
    volume: "99",
    year: "2011",
    pages: "193702",
    citations: 9,
    tags: ["Acoustic", "Microbubbles", "Vessels"],
  },
  {
    title: "The acoustic scatter from single bisphere microbubbles",
    authors: "DH Thomas, MB Butler, A Dermitzakis, T Anderson, WN McDicken, V Sboros",
    journal: "Ultrasound in Medicine and Biology",
    volume: "36",
    year: "2010",
    pages: "1884-1892",
    citations: 9,
    tags: ["Acoustic", "Microbubbles", "Scatter"],
  },
  {
    title: "Acoustic Investigation of Microbubble Response to Medical Imaging Ultrasound Pulses",
    authors: "DH Thomas",
    journal: "The University of Edinburgh",
    year: "2010",
    citations: 3,
    tags: ["Acoustic", "Microbubbles", "Ultrasound"],
  },
  {
    title: "Single microbubble acoustics in small tubes",
    authors: "MB Butler, A Dermitzakis, D Thomas, P Looney, S Pye, V Sboros",
    journal: "Proc. Int. Conf. Acoustics",
    year: "2010",
    citations: 3,
    tags: ["Microbubble", "Acoustics", "Tubes"],
  },
  {
    title: "Acoustic detection of microbubble resonance",
    authors: "DH Thomas, P Looney, R Steel, N Pelekasis, WN McDicken, T Anderson, V Sboros",
    journal: "Applied Physics Letters",
    volume: "94",
    year: "2009",
    pages: "243902",
    citations: 37,
    tags: ["Acoustic", "Microbubble", "Resonance"],
  },
  {
    title: "Single microbubble response using pulse sequences: initial results",
    authors: "DH Thomas, MB Butler, T Anderson, R Steel, SD Pye, M Poland, T Brock-Fisher, WN McDicken, V Sboros",
    journal: "Ultrasound in Medicine and Biology",
    volume: "35",
    year: "2009",
    pages: "112-119",
    citations: 26,
    tags: ["Microbubble", "Pulse Sequences", "Response"],
  },
  {
    title: "Optical observations of microbubble oscillation in small tubes",
    authors: "D Thomas, V Sboros, M Emmer, HJ Vos, N de Jong",
    journal: "Ultrasonics Symposium (IUS), 2009 IEEE International",
    year: "2009",
    pages: "2782-2784",
    citations: 4,
    tags: ["Optical", "Microbubble", "Oscillation"],
  },
  {
    title: "Survival of single microbubbles insonated in solution and in narrow tubes",
    authors: "M Butler, A Dermitzakis, D Thomas, SD Pye, V Sboros",
    journal: "Ultrasonics Symposium (IUS), 2009 IEEE International",
    year: "2009",
    pages: "1259-1261",
    citations: 3,
    tags: ["Microbubble", "Survival", "Tubes"],
  },
  {
    title: "The acoustic response from individual attached and unattached rigid shelled microbubbles",
    authors: "MB Butler, DH Thomas, SD Pye, CM Moran, WN McDicken, V Sboros",
    journal: "Applied Physics Letters",
    volume: "93",
    year: "2008",
    pages: "223906",
    citations: 12,
    tags: ["Acoustic", "Microbubbles", "Rigid Shelled"],
  },
  {
    title: "A realistic model for ultrasound contrast microbubbles: initial results",
    authors: "P Looney, D Thomas, R Steel, T Anderson, N Pelekasis, V Sboros",
    journal: "WIMRC Cavitation Forum",
    year: "2008",
    pages: "157-164",
    citations: 3,
    tags: ["Ultrasound", "Contrast", "Microbubbles"],
  },
  {
    title: "Comparison of the acoustic response of attached and unattached BiSphere™ microbubbles",
    authors: "MB Butler, DH Thomas, CM Moran, WN McDicken, V Sboros, SD Pye",
    journal: "Ultrasonics Symposium, 2008. IUS 2008. IEEE",
    year: "2008",
    pages: "1683-1685",
    citations: 2,
    tags: ["Acoustic", "Microbubbles", "BiSphere"],
  },
  {
    title:
      "Single Microbubble Acoustics with Signal Processing: Initial Experience with Amplitude Modulated Pulse Sequences",
    authors: "DH Thomas, MB Butler, T Anderson, WN McDicken, V Sboros",
    journal: "Ultrasonics Symposium, 2007. IEEE",
    year: "2007",
    pages: "2223-2226",
    citations: 4,
    tags: ["Microbubble", "Acoustics", "Signal Processing"],
  },
]
